### ISSUE TITLE
Diagrams not created if built inside docker container

### ISSUE THREAD

**Issue by AndreasGassmann** [eFrane/vuepress-plugin-mermaidjs#12]
First of all thanks for the plugin, it's very easy to set up and works well, except in the following case:

I noticed that when building the docs inside a docker container, the diagrams are not created. Instead, the regular text is shown. I checked the HTML files and it looks like there is no svg but just the plain HTML:

![mermaid-not-working](https://user-images.githubusercontent.com/680814/79483329-7772cb80-8012-11ea-947f-db7a048fb768.png)

When building the same project outside of the docker container, it works flawlessly. (To clarify, inside the docker both the dev and prod build don't work, outside both work).

I was not able to see any errors, but it's my first time working with vuepress, so I'm not sure if they are turned off by default.

The project I'm working on is open source, so if you have time you can take a look and reproduce it.

Docs: http://docs.walletbeacon.io/
Github: https://github.com/airgap-it/beacon-sdk

I tried to solve the issue myself before opening this ticket, the only thing I noticed in other docker containers related to mermaid is that they install phantomjs. I tried that, but it still didn't work.

BTW, the dockerfile I used is in that repo, I've set it up to use it with the VSCode Remote Development plugin. https://code.visualstudio.com/docs/remote/containers

**Comment by eFrane** [comment]
That sounds weird to me. I have VuePress with this Plugin running inside a docker container (prod build) thus it is definitely possible.

Just so that I check the right file, the Dockerfile is https://github.com/airgap-it/beacon-sdk/blob/master/Dockerfile?

**Comment by AndreasGassmann** [comment]
Sorry didn't remember there were 2 Dockerfiles.

No, the one I'm using is this: https://github.com/airgap-it/beacon-sdk/blob/master/.devcontainer/Dockerfile

**Comment by eFrane** [comment]
This is probably not the answer you were hoping for but for now it's all I have: It works for me.

The steps I did:

1. Clone the repo
2. Manually build the docker container:

``` bash
cd .devcontainer
docker build -t beacon-sdk-vuepress .
```

3. Run the container with port binding

```
docker run --rm -it -v$(pwd):/data -p8080:8080 beacon-sdk-vuepress:latest bash
```

4. Build and run the docs inside the container, available at `http://localhost:8080/` outside of the container

```
npm i
npm run docs:dev
```

I'm not sure if this is of any help. I have no experience with VSCode Remote Development but suspect the issue might lie within that configuration. Hope, this helps.

**Comment by AndreasGassmann** [comment]
I set everything up like I usually do on another machine and it just worked.

Then I removed all the images and cleaned everything on the machine I tried it originally, now it works as well.

I was looking into this issue for a couple of hours and I was sure it was related to docker, but well... Sorry for wasting your time.
