### ISSUE TITLE
Missing dependencies

### ISSUE THREAD

**Issue by stefnats** [eFrane/vuepress-plugin-mermaidjs#13]
Hi,

i'm using vuepress version `vuepress/1.3.1 darwin-x64 node-v12.14.1` with vuepress-plugin-mermaidjs `^1.5.1`.

However i get many compilation errors like:

```
error vuepress-plugin-mermaidjs apply chainMarkdown failed.
Error: Cannot find module '@vuepress/shared-utils'
Require stack:
- /Users/blabla/node_modules/vuepress-plugin-mermaidjs/src/markdownItPlugin.js
- /Users/blabla/node_modules/vuepress-plugin-mermaidjs/src/index.js
- /Users/blabla/.nvm/versions/node/v12.14.1/lib/node_modules/vuepress/node_modules/@vuepress/shared-utils/lib/moduleLoader.js
- /Users/blabla/.nvm/versions/node/v12.14.1/lib/node_modules/vuepress/node_modules/@vuepress/shared-utils/lib/index.js
```

I couldn't help myself but add the missing dependencies myself in package.json:

```
"devDependencies": {
    "@vue/component-compiler-utils": "^3.1.2",
    "@vuepress/shared-utils": "^1.4.1",
    "lru-cache": "^5.1.1",
    "markdown-it-emoji": "^1.4.0",
    "toml": "^3.0.0",
    "vuepress-plugin-mermaidjs": "^1.5.1"
  },
```

Why did i have to do this, is anything here unsupported or weird about my setup?

Anyways thanks for the amazing plugin, saves me a lot of time and makes maintaining docs easy.

*EDIT* I'm using mermaid `8.4.8` (`8.5.0` doesn't seem to work)

**Comment by eFrane** [comment]
I bumped the `devDependency` of VuePress in this repository to 1.3 and don't see any issues. Also wasn't required to add `@vuepress/shared-utils`. 🤔 

Are you using `yarn` or `npm`?

**Comment by stefnats** [comment]
I'm using `yarn` as it is recommended by Vue/Vuepress

**Comment by eFrane** [comment]
I'm sorry but I think I'm going to have to close this as I do not find myself able to reproduce your error. Feel free to re-open and add more info.
