### ISSUE TITLE
The generated svg size doesn't match the mobile device

### ISSUE THREAD

**Issue by huxiaoxi1992** [eFrane/vuepress-plugin-mermaidjs#14]
![image](https://user-images.githubusercontent.com/17983389/82289583-b14f3d00-99d7-11ea-9725-2f0bb0b2fb12.png)

Please consider add "style:100%" to the svg element.

**Comment by eFrane** [comment]
I'm on it. The change itself is super simple and makes sense but I want to make sure that this doesn't interfere with navigation in larger diagrams.

**Comment by eFrane** [comment]
This is implemented and will be in the next release.
