### ISSUE TITLE
Make mermaid a peer dependency so it can easily be upgraded

### ISSUE THREAD

**Issue by mmc41** [eFrane/vuepress-plugin-mermaidjs#15]
First of all, thanks for this wonderfull vuepres plugin for mermaid. Nice work!

The current plugin depends on an older mermaid version as a dependency and I would like to upgrade to the newest mermaid version 8.6.0. Instead of having to continuously update the plugin for each new version of mermaid, it seems to me it would be better to change the dependency to a peer dependency. This way, the user can update mermaid him/her-self without having to update this plugin (exception: unless something changes in mermaid in a way that is not backward compatible).

**Comment by eFrane** [comment]
Thank you :)

I did previously consider making mermaid a peer dependency. However, two things held me back.

1) What you're mentioning in the brackets. It's not that Mermaid breaks often, it actually to my memory never does. But it's API changes from time to time and I would rather not provide a plugin depending on a maybe broken API implementation. The other solution to this would be to bloat the plugin over time to handle more and more different mermaid versions which also does not feel like a good option.

2) I simply don't like peer dependencies. It's a weird concept. It's like composer suggestions. Package management should be explicit. If that means things aren't up to date then there likely is a reason for it.

Addendum: The reason, of course, why I didn't upgrade the lib's dependencies to the current mermaid is that Dependabot seems to dislike this repository and I didn't notice there's a new version. I will investigate this.

**Comment by eFrane** [comment]
- `v1.6.0` has the current mermaid version
- I reconfigured Dependabot to not miss mermaid upgrades anymore, timely library updates will follow when mermaid gets an update
