### ISSUE TITLE
Compatible with vuepress 0.14?

### ISSUE THREAD

**Issue by carlo-quinonez** [eFrane/vuepress-plugin-mermaidjs#2]
What version of vuepress does this plugin work with? I tried it with 0.14.8 but doesn't seem to be working.

**Comment by eFrane** [comment]
Hello @carlo-quinonez, sorry for getting back to you this late - when I intended to answer your question I discovered that the whole plugin was broken. Now it works again.

Unfortunately, this plugin only works with VuePress 1.0 and onwards. To my knowledge v0.14 didn't have a Plugin API yet.

If you're unable to upgrade your VuePress installation you can try following a blog post I wrote about this a while back: https://meanderingsoul.com/dev/2019/05/adding-mermaid-js-support-to-vuepress. No guarantees on this working out of the box but maybe it has some guidance value.

**Comment by carlo-quinonez** [comment]
That makes sense. I was able to get Mermaid working fairly easily using [markdown-it-textual-uml](markdown-it-textual-uml).
