### ISSUE TITLE
More graphs

### ISSUE THREAD

**Issue by mmc41** [eFrane/vuepress-plugin-mermaidjs#26]
Again thanks for this great plugin and for updating to latest mermaid! .. I have been looking at more types of graph support than mermaidjs offers in vuepress and found [markvis](https://github.com/geekplux/markvis) that also works inside markdown. See below:

![markvis](https://user-images.githubusercontent.com/17993/89712893-1fcae800-d994-11ea-8d83-86617af10414.png)

What would be the best way to support this - could this plugin be made to support multiple engines ? (preferable I think that with multiple plugins that are doing almost the same integration to vuepress).

P.S: For feature completeness, there is of cause also [GraphViz](https://github.com/geeklearningio/graphviz-markdown-preview) as shown below:

![graphviz](https://user-images.githubusercontent.com/17993/89712995-cf07bf00-d994-11ea-8fd3-2f91c1da39f8.png)

**Comment by eFrane** [comment]
Thanks for opening the issue!

Yeah, I think that would have to be separate package(s). I have also been eyeing PlantUML for quite a while now. However, I would rather like to see more diagramming types come to Mermaid instead. Hm… I'll think about a possible solution. Maybe one graphing plugin which itself can have several adapters like Mermaid, Markvis, etc.

**Comment by mmc41** [comment]
Sounds great with multiple adapters in the same vuepress plugin.

It does not look like Mermaid will have that many more diagrams soon, so the adapter approach would be best I think.

**Comment by eFrane** [comment]
I'll close this. This is a plugin for mermaidjs, turning it into a generic graph library support plugin would really explode the scope and make things harder for the current users.
