### ISSUE TITLE
[Feature Request] Add a class name to the "div" that wraps the mermaid diagram

### ISSUE THREAD

**Issue by JamesChenX** [eFrane/vuepress-plugin-mermaidjs#32]
Thanks for your repo!
Could you help add a class name like "mermaid-container" or another name to the "div" that wraps the mermaid diagram like the following image shows?

Motivation: We can add a custom style according to the class name.

![image](https://user-images.githubusercontent.com/44962329/92459463-5301d080-f1f9-11ea-94b0-f89bcdaa2db5.png)

**Comment by eFrane** [comment]
I was about to say that this should already if you use the tag-based variant of the plugin:

```markdown
<mermaid class="mermaid-container">
...
</mermaid>
```

But yeah, I can see how that would be tedious if there are a lot of diagrams which get the same layout class.

I am not sure, however, if I want to add this to the plugin or if my recommendation is for you to e.g. create a wrapper component adding the class.
