### ISSUE TITLE
Support VuePress v2?

### ISSUE THREAD

**Issue by lptn** [eFrane/vuepress-plugin-mermaidjs#64]
Do you have any plans to support VuePress v2 (which one in beta now)?

**Comment by eFrane** [comment]
I absolutely want to support Vuepress 2. I tried my hands at it a while ago, but did hit a few walls with the plugin api at the time. Until I get to this, if anyone seeing this issue wants to make an attempt I'm more than happy to help polish it for merging. (please don't read this as me not wanting to do the work, I just want to point out that contributions are welcome.)

**Comment by eFrane** [comment]
So, turns out I'm going to have to basically rewrite this Plugin because the Vue 3/Vuepress 2 combo feels very much like Angular 2 all over again. Anyone wanting to chip in ideas on how long I should maintain a Vuepress 1 version is welcome to do so. :)

**Comment by jeremycloud** [comment]
@eFrane This is still a work in progress, I have a preliminary V2 plugin working here if you are interested. https://gitlab.com/sloud/vuepress-plugin-default-theme-mermaid

**Comment by eFrane** [comment]
@jeremycloud This looks awesome. Would you be okay with me borrowing (with attribution of course) a little bit from your work?

**Comment by jeremycloud** [comment]
@eFrane yeah go for it.

**Comment by eFrane** [comment]
I (finally, sorry), just released v2.0.0-beta.1 with Vuepress 2 support. Please don't hesitate to open new issues regarding broken things/missing features. I'll close this one though as it only pertains to general support.

**Comment by MeikelLP** [comment]
@eFrane does not really work for me:

```
Error: Cannot find module '@vuepress/shared-utils'
Require stack:
- [...]\node_modules\vuepress-plugin-mermaidjs\src\markdownItPlugin.js
```

my package.json
```json
"devDependencies": {
    "@vuepress/plugin-search": "^2.0.0-beta.37",
    "vuepress": "^2.0.0-beta.37",
    "vuepress-plugin-mermaidjs": "^2.0.0-beta.2"
}
```

I assume a CI would've seen this. Maybe you should fix Travis as well?

**Comment by MeikelLP** [comment]
Also the source code does not work on windows (at least for me):

```sh
npx vuepress build docs
```

causes the file `docs/.vuepress/.temp/internal/clientAppEnhancements.js` to be built. Sadly this file contains an invalid path (Windows backslash dilemma):

```js
// other imports
import clientAppEnhance3 from 'D:/projekte/github/vuepress-plugin-mermaidjs/node_modules/@vuepress/theme-default/lib/client/clientAppEnhance.js'
import clientAppEnhance4 from 'D:\projekte\github\vuepress-plugin-mermaidjs\src\clientAppEnhance.js'
```

Maybe this is a vite bug. I don't know. Just wanted to mention it. The dirty fix is:

```js
    clientAppEnhanceFiles: path.resolve(__dirname, 'clientAppEnhance.js').replace(/\\/g, '/')
```

in `src/index.js`

**Comment by kidonng** [comment]
I wrote a patch for latest VuePress 2 beta (as of now 2.0.0-beta.51): https://github.com/v2fly/v2fly-github-io/blob/991b634231afb5957fc1eef198b8b9e0f92f571e/patches/vuepress-plugin-mermaidjs%2B2.0.0-beta.2.patch
